### ISSUE TITLE
Failed to load File

### ISSUE THREAD

**Issue by SKAUL05** [rickardl/tflint-action#2]
Have my terraform files inside `src` folder. Using below action to run 

```
jobs:
  lint:
    name: "Lint Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickardl/tflint-action@v1
        with:
          tflint_actions_folder:  src/
```
But it is giving following error.
```
Failed to parse CLI arguments. An error occurred:
Error: Failed to load ``: File not found
```

Any help would be appreciated. @rickardl
